### ISSUE TITLE
Corrections to paper

### ISSUE THREAD

**Issue by feynmanliang** [ekzhang/langevin-music#1]
Hi there, I'm there author of BachBot. Your work is very exciting and I'm happy to see it!

I wanted to point out some corrections to https://www.ekzhang.com/assets/pdf/Generative_Music_Modeling.pdf. In particular, the first reference to BachBot (bottom of p1) is misattributted to DeepBach. Furthermore, the two encodings are quite similar (Gaetan and I were both working on this in 2016 and BachBot was open source the entire time) but the music encoding format (discetization to sixteenths, represent note durations using ties across frames, inclusion of fermatas) actually originates from BachBot (see the citation on https://arxiv.org/pdf/1612.01010.pdf page 2 across the fold). DeepBach improves this encoding (among many other things) by adding the key signature to the encoding metadata.

**Comment by ekzhang** [comment]
Hey, thanks for passing on the message! Really excited (and surprised!) that you saw this project. BachBot was a big inspiration for @romil797 and I.

Sorry about the typo on p.1, we accidentally reversed [8] and [11]. I'll also update the other mention about the music encoding format.

If you're still working on projects in this field, I would love to collaborate!

**Comment by feynmanliang** [comment]
Thanks you! Yeah I'm sure we can figure something out; I'll send you an e-mail to follow up.
